footprint: [[-0.15, -0.25], [-0.15, 0.25], [0.15, 0.25], [0.15, -0.25]]
footprint_padding: 0.01


robot_base_frame: /robot/base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.1

resolution: 0.05

obstacle_range: 3.0
raytrace_range: 4.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true


#observation_sources: scan

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /robot/hokuyo, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
